apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: hello-ratelimit
    descriptors:
    - key: PATH
      value: "/version"
      rate_limit:
        unit: minute
        requests_per_unit: 20
    - key: PATH
      rate_limit:
        unit: minute
        requests_per_unit: 100
