apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: jwt-request-authentication
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      app: external-ingress-gateway
  jwtRules:
  - issuer: https://aeldridge.au.auth0.com/
    jwksUri: https://aeldridge.au.auth0.com/.well-known/jwks.json
    outputPayloadToHeader: X-Auth-Payload
