apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: internal-gateway
  namespace: istio-ingress
spec:
  selector:
    app: internal-ingress-gateway
  # TODO: Ideally, just leave these as standard ports: 80, 443, etc
  # across all gateways. Prefer not to cater for k3d and have separate
  # ports (or at least do via Kustomize).
  servers:
  - port:
      number: 9080
      name: http
      protocol: HTTP
    hosts:
    - api.internal.00rg.com
