apiVersion: v1
kind: Service
metadata:
  name: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/http-gateway
  http:
  - match:
    - uri:
        prefix: /httpbin/
    rewrite:
      uri: /
    route:
    - destination:
        host: httpbin
