apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: root-vpc
  # See: https://crossplane.io/docs/v1.10/concepts/managed-resources.html#external-name
  # annotations:
    # crossplane.io/external-name: vpc-123
spec:
  forProvider:
    region: ap-southeast-2
    enableDnsHostNames: true
    enableDnsSupport: true
    cidrBlock: 10.0.0.0/16
    tags:
      - key: Name
        value: root-vpc
  providerConfigRef:
    name: aws-provider-config
