apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      serviceAccountName: hello
      containers:
      - name: hello
        image: k3d-local-registry:5555/hello:0.0.1
        # image: ashlineldridge/hello:0.0.1
        env:
        - name: EXTERNAL_URL
          value: http://httpbin.httpbin.svc.cluster.local/get
